--SSS_NO_MONETARIA_OMNIA_QUERY.sql
WITH SELECTBT AS (
    SELECT B.BUSINESS_TEMPLATE_ID,
           CASE
            WHEN LENGTH(SUBSTR(B.SHORT_NAME,0,INSTR(B.SHORT_NAME,'ÿ') - 1) ) > 0 THEN SUBSTR(B.SHORT_NAME,0,INSTR(B.SHORT_NAME,'ÿ') - 1)
            ELSE SHORT_NAME
        END
    AS SHORT_NAME
    FROM EEFISA.TAPD_BUSINESS_TEMPLATE B
    WHERE B.BUSINESS_TEMPLATE_ID IN (
        SELECT BUSINESS_TEMPLATE_ID
        FROM TAUD_ACTIVITY_LOG
        WHERE TRUNC(RECORD_DATE) = TRUNC(SYSDATE - 1)
                 --user_id = &user_id
              AND   BUSINESS_TEMPLATE_ID IS NOT NULL
        UNION ALL
        SELECT BUSINESS_TEMPLATE_ID
        FROM TAUD_ACTIVITY_LOG_HIS
        WHERE TRUNC(RECORD_DATE) = TRUNC(SYSDATE - 1)
                 --user_id = &user_id
              AND   BUSINESS_TEMPLATE_ID IS NOT NULL
    )
),SELECTQT AS (
    SELECT Q.QUERY_TEMPLATE_ID,
           CASE
            WHEN LENGTH(SUBSTR(Q.SHORT_NAME,0,INSTR(Q.SHORT_NAME,'ÿ') - 1) ) > 0 THEN SUBSTR(Q.SHORT_NAME,0,INSTR(Q.SHORT_NAME,'ÿ') - 1)
            ELSE SHORT_NAME
        END
    AS SHORT_NAME
    FROM TAPD_QUERY_TEMPLATE Q
    WHERE Q.QUERY_TEMPLATE_ID IN (
        SELECT QUERY_TEMPLATE_ID
        FROM TAUD_ACTIVITY_LOG
        WHERE TRUNC(RECORD_DATE) = TRUNC(SYSDATE - 1)
                 --and user_id = &user_id
              AND   QUERY_TEMPLATE_ID IS NOT NULL
        UNION ALL
        SELECT QUERY_TEMPLATE_ID
        FROM TAUD_ACTIVITY_LOG_HIS
        WHERE TRUNC(RECORD_DATE) = TRUNC(SYSDATE - 1)
                 --and user_id = &user_id
              AND   QUERY_TEMPLATE_ID IS NOT NULL
    )
) SELECT H.INTERNAL_SESSION_ID,
         H.EVENT_TYPE,
         (
    SELECT CT.VALUE
    FROM TGEN_CATALOGUE_ITEM CT
    WHERE H.EVENT_TYPE = CT.ITEM_ID
          AND   CT.CATALOGUE_ID = 1
) EVENTO,
--    to_char( h.process_date,'DD/MM/YYYY HH24:MI:SS') as process_date,
--    to_char( h.record_date,'DD/MM/YYYY HH24:MI:SS') as record_date,
         H.PROCESS_DATE,
         H.RECORD_DATE,
         H.SESSION_ID,
         H.TERMINAL_ID,
         H.LOGON_ATTEMPT,
         H.USER_ID,
         H.SIGN_ON_NAME,
         H.ACTION_ID,
         H.A_CHANNEL_ID,
         H.BUSINESS_TEMPLATE_ID,
         (
    SELECT SHORT_NAME
    FROM SELECTBT
    WHERE BUSINESS_TEMPLATE_ID = H.BUSINESS_TEMPLATE_ID
) AS SHORT_NAME_BT,
         H.QUERY_TEMPLATE_ID,
         (
    SELECT SHORT_NAME
    FROM SELECTQT
    WHERE QUERY_TEMPLATE_ID = H.QUERY_TEMPLATE_ID
) AS SHORT_NAME_QT,
         H.RECORD_NUMBER,
         'log' AS TABLA,
         H.URL_QUERY_STRING,
         H.CLIENT_IP_ADDRESS,
         H.BROWSER_NAME,
         H.AUTH_PASSWORD,
         H.COOKIE,
         H.REMOTE_ADR,
         H.CDN_IP,
         H.USER_AGENT
  FROM TAUD_ACTIVITY_LOG H
  WHERE TRUNC(RECORD_DATE) BETWEEN TO_DATE(:P_FECHAHORA_INICIO,'YYYYMMDDHH24MISS') AND TO_DATE(:P_FECHAHORA_FINAL,'YYYYMMDDHH24MISS') 
  --WHERE TRUNC(RECORD_DATE) = TRUNC(SYSDATE - 1)
         --and user_id=&user_id 
UNION ALL
SELECT H.INTERNAL_SESSION_ID,
       H.EVENT_TYPE,
       (
    SELECT CT.VALUE
    FROM TGEN_CATALOGUE_ITEM CT
    WHERE H.EVENT_TYPE = CT.ITEM_ID
          AND   CT.CATALOGUE_ID = 1
) EVENTO,
--    to_char( h.process_date,'DD/MM/YYYY HH24:MI:SS') as process_date,
--    to_char( h.record_date,'DD/MM/YYYY HH24:MI:SS') as record_date,
       H.PROCESS_DATE,
       H.RECORD_DATE,
       H.SESSION_ID,
       H.TERMINAL_ID,
       H.LOGON_ATTEMPT,
       H.USER_ID,
       H.SIGN_ON_NAME,
       H.ACTION_ID,
       H.A_CHANNEL_ID,
       H.BUSINESS_TEMPLATE_ID,
       (
    SELECT SHORT_NAME
    FROM SELECTBT
    WHERE BUSINESS_TEMPLATE_ID = H.BUSINESS_TEMPLATE_ID
) AS SHORT_NAME_BT,
       H.QUERY_TEMPLATE_ID,
       (
    SELECT SHORT_NAME
    FROM SELECTQT
    WHERE QUERY_TEMPLATE_ID = H.QUERY_TEMPLATE_ID
) AS SHORT_NAME_QT,
       H.RECORD_NUMBER,
       'his' AS TABLA,
       H.URL_QUERY_STRING,
       H.CLIENT_IP_ADDRESS,
       H.BROWSER_NAME,
       H.AUTH_PASSWORD,
       H.COOKIE,
       H.REMOTE_ADR,
       H.CDN_IP,
       H.USER_AGENT
FROM TAUD_ACTIVITY_LOG_HIS H
WHERE TRUNC(RECORD_DATE) BETWEEN TO_DATE(:P_FECHAHORA_INICIO,'YYYYMMDDHH24MISS') AND TO_DATE(:P_FECHAHORA_FINAL,'YYYYMMDDHH24MISS') 
--WHERE TRUNC(RECORD_DATE) = TRUNC(SYSDATE - 1)
     --and user_id=&user_id 
;
     
     
/*SELECT TO_CHAR(A.INTERNAL_SESSION_ID) AS NO_TRX,
         A.RECORD_DATE AS FECHA,
         A.SHORT_NAME_BT AS TIPO_TRX,
         A.SHORT_NAME_BT AS CATEG_TRANS,
         A.EVENTO AS EVENTO,
         NULL AS ESTATUS,
         'BANCA EN LINEA' AS CANAL,
         NULL AS OFICINA_DEL_TRANSACCION,
         NULL AS TIPO_CLIENTE,
         NULL AS NO_CONTRATO,
         NULL AS COD_COMERCIO,
         NULL AS NOMBRE_COMERCIO,
         NULL AS NO_SOCIO,
         NULL AS NO_SUCURSAL_SOCIO,
         NULL AS NO_AGENCIA,
         NULL AS COD_CAJERO,
         NULL AS NUMERO_SIB,
         NULL AS COD_OPERACION_SIB,
         TO_CHAR(A.USER_ID) AS NO_SESION,
         NULL AS NO_APROBACION_TARJETA,
         NULL AS COD_TRX_PROCESADOR,
         NULL AS COD_PROCESADOR,
         NULL AS NOMBRE_RED,
         NULL AS NO_CTA_ORIGEN,
         NULL AS TIPO_CTA_ORIGEN,
         NULL AS NO_CTA_DESTINO,
         NULL AS TIPO_CTA_DESTINO,
         NULL AS CTA_ENTIDAD_REMITENTE,
         NULL AS CLIENTE_REMITENTE,
         NULL AS TIPO_ID_REMITENTE,
         NULL AS ENTIDAD_REMITENTE,
         NULL AS CTA_ENTIDAD_RECEPTORA,
         NULL AS CLIENTE_RECEPTOR,
         NULL AS TIPO_ID_RECEPTOR,
         NULL AS IDENTI_RECEPTOR,
         NULL AS ENTIDAD_RECEPTORA,
         NULL AS EMAIL,
         NULL AS ESTATUS_CUENTA,
         A.SIGN_ON_NAME AS REFERENCIA_USUARIO,
         NULL AS MONEDA_ORIGEN,
         NULL AS MONTO_ORIGEN,
         NULL AS MONEDA_DESTINO,
         NULL AS MONTO_DESTINO,
         NULL AS SUBTOTAL,
         NULL AS MONTO_COMISION_USUARIO,
         NULL AS IMPUESTO,
         NULL AS MONTO_IMPUESTO,
         NULL AS MONTO_IMPUESTO_2_,
         NULL AS COMISION_EN_LINEA,
         A.SHORT_NAME_BT AS DETALLE_TRX,
         NULL AS REFERENCIA,
         NULL AS ENVIA_NOTIFICACION,
         NULL AS EMAIL_BENEFICIARIO,
         A.SIGN_ON_NAME AS USUARIO,
         NULL AS COD_RESPUESTA_BACKEND,
         NULL AS DESCRIPCION_BACKEND,
         NULL AS NO_APROBACION_TRADER,
         NULL AS CATEGORIA_CTA_ORIGEN,
         NULL AS SUBCATEGORIA_CTA_ORIGEN,
         NULL AS CATEGORIA_CTA_DESTINO,
         NULL AS SUBCATEGORIA_CTA_DESTINO,
         NULL AS RESPONSABLE
         select a.*
  FROM (     
) A
    
    --order by internal_session_id, record_date
    --order by internal_session_id, record_date desc 

ORDER BY A.INTERNAL_SESSION_ID DESC
;*/

SELECT MAX(RECORD_DATE) FROM TAUD_ACTIVITY_LOG_HIS;

SELECT CT.VALUE
FROM TGEN_CATALOGUE_ITEM CT
WHERE CT.CATALOGUE_ID = 1;