--SSS_NO_MONETARIA_OMNIA_QUERY.sql
DECLARE
    nClienteId Varchar2(35) := 2878;
    P_FECHAHORA_INICIO DATE := TO_DATE('20230610000000','YYYYMMDDHH24MISS');
    P_FECHAHORA_FINAL DATE :=  TO_DATE('20230610235959','YYYYMMDDHH24MISS');
    P_INTERNAL_SESSION_ID_INICIO NUMBER(18) := 0;
    P_INTERNAL_SESSION_ID_FINAL NUMBER(18) :=  999999999999999999;
BEGIN
    EAPPFISA.Set_Generic_ctx('P_FECHAHORA_INICIO',TO_CHAR(P_FECHAHORA_INICIO,'YYYYMMDDHH24MISS'), nClienteId);
    EAPPFISA.Set_Generic_ctx('P_FECHAHORA_FINAL',TO_CHAR(P_FECHAHORA_FINAL,'YYYYMMDDHH24MISS'), nClienteId);
    EAPPFISA.Set_Generic_ctx('P_INTERNAL_SESSION_ID_INICIO',TRIM(TO_CHAR(P_INTERNAL_SESSION_ID_INICIO)),nClienteId);
    EAPPFISA.Set_Generic_ctx('P_INTERNAL_SESSION_ID_FINAL',TRIM(TO_CHAR(P_INTERNAL_SESSION_ID_FINAL)), nClienteId);
END;

CREATE OR REPLACE VIEW EEFISA.SSS_NO_MONETARIA_OMNIA_QUERY AS
--ESQUEMA PRINCIPAL EEFISA, HABILITADO EN ADICICON PARA EL ESQUEMA EAPPFISA
    WITH SELECTBT AS (
        SELECT B.BUSINESS_TEMPLATE_ID,
               CASE
                WHEN LENGTH(SUBSTR(B.SHORT_NAME,0,INSTR(B.SHORT_NAME,'ÿ') - 1) ) > 0 THEN SUBSTR(B.SHORT_NAME,0,INSTR(B.SHORT_NAME,'ÿ') - 1)
                ELSE SHORT_NAME
            END
        AS SHORT_NAME
        FROM EEFISA.TAPD_BUSINESS_TEMPLATE B
    ),SELECTQT AS (
        SELECT Q.QUERY_TEMPLATE_ID,
               CASE
                WHEN LENGTH(SUBSTR(Q.SHORT_NAME,0,INSTR(Q.SHORT_NAME,'ÿ') - 1) ) > 0 THEN SUBSTR(Q.SHORT_NAME,0,INSTR(Q.SHORT_NAME,'ÿ') - 1)
                ELSE SHORT_NAME
            END
        AS SHORT_NAME
        FROM EEFISA.TAPD_QUERY_TEMPLATE Q
    ) SELECT H.ROWID AS ROW_ID,
             'log' AS TABLA,
             H.INTERNAL_SESSION_ID,
             H.EVENT_TYPE,
             CT.VALUE AS EVENTO,
             H.PROCESS_DATE,
             H.RECORD_DATE,
             H.SESSION_ID,
             H.TERMINAL_ID,
             H.SIGN_ON_NAME,
             H.LOGON_ATTEMPT,
             H.USER_ID,
             H.AREA_DEF_ID,
             H.AREA_ID,
             H.COMPANY_ID,
             H.APPLICATION_ID,
             H.BUSINESS_TEMPLATE_ID,
             SELECTBT.SHORT_NAME AS SHORT_NAME_BT,
             H.ACTION_ID,
             H.APPLICATION_PK,
             H.QUERY_TEMPLATE_ID,
             SELECTQT.SHORT_NAME AS SHORT_NAME_QT,
             H.RECORD_NUMBER,
             H.KILL_SESSION_IMMEDIATELY,
             H.ACTIVATE_FOR_TRACE,
             H.A_CHANNEL_ID,
             H.A_PERSON_ID,
             H.COOKIE,
             H.LONGITUD,
             H.LATITUD,
             H.MBL_MODEL,
             H.MBL_SO,
             H.REMOTE_HOST,
             H.REMOTE_ADR,
             H.CDN_IP,
             H.CLIENT_IP,
             H.USER_AGENT,
             H.URL_QUERY_STRING,
             H.BROWSER_LANGUAGE,
             H.CLIENT_IP_ADDRESS,
             H.BROWSER_NAME,
             H.AUTH_PASSWORD
      FROM EEFISA.TAUD_ACTIVITY_LOG H
    LEFT JOIN EEFISA.TGEN_CATALOGUE_ITEM CT ON ( H.EVENT_TYPE = CT.ITEM_ID
                                                 AND CT.CATALOGUE_ID = 1 )
    LEFT JOIN SELECTBT ON ( SELECTBT.BUSINESS_TEMPLATE_ID = H.BUSINESS_TEMPLATE_ID )
    LEFT JOIN SELECTQT ON ( SELECTQT.QUERY_TEMPLATE_ID = H.QUERY_TEMPLATE_ID )
  --WHERE RECORD_DATE BETWEEN TO_DATE(:P_FECHAHORA_INICIO,'YYYYMMDDHH24MISS') AND TO_DATE(:P_FECHAHORA_FINAL,'YYYYMMDDHH24MISS') 
      WHERE H.RECORD_DATE BETWEEN NVL(TO_DATE(SYS_CONTEXT('Generic_ctx','P_FECHAHORA_INICIO'),'YYYYMMDDHH24MISS'),TRUNC(SYSDATE) - 10) AND NVL(TO_DATE(SYS_CONTEXT('Generic_ctx','P_FECHAHORA_FINAL'),'YYYYMMDDHH24MISS'),TRUNC(SYSDATE) + 1)
            AND   H.INTERNAL_SESSION_ID BETWEEN NVL(TO_NUMBER(SYS_CONTEXT('Generic_ctx','P_INTERNAL_SESSION_ID_INICIO') ),0) AND NVL(TO_NUMBER(SYS_CONTEXT('Generic_ctx','P_INTERNAL_SESSION_ID_FINAL') ),999999999999999999)
  --WHERE TRUNC(RECORD_DATE) = TRUNC(SYSDATE - 1) and user_id=:user_id 
    UNION ALL
    SELECT H.ROWID AS ROW_ID,
           'his' AS TABLA,
           H.INTERNAL_SESSION_ID,
           H.EVENT_TYPE,
           CT.VALUE AS EVENTO,
           H.PROCESS_DATE,
           H.RECORD_DATE,
           H.SESSION_ID,
           H.TERMINAL_ID,
           H.SIGN_ON_NAME,
           H.LOGON_ATTEMPT,
           H.USER_ID,
           H.AREA_DEF_ID,
           H.AREA_ID,
           H.COMPANY_ID,
           H.APPLICATION_ID,
           H.BUSINESS_TEMPLATE_ID,
           SELECTBT.SHORT_NAME AS SHORT_NAME_BT,
           H.ACTION_ID,
           H.APPLICATION_PK,
           H.QUERY_TEMPLATE_ID,
           SELECTQT.SHORT_NAME AS SHORT_NAME_QT,
           H.RECORD_NUMBER,
           H.KILL_SESSION_IMMEDIATELY,
           H.ACTIVATE_FOR_TRACE,
           H.A_CHANNEL_ID,
           H.A_PERSON_ID,
           H.COOKIE,
           H.LONGITUD,
           H.LATITUD,
           H.MBL_MODEL,
           H.MBL_SO,
           H.REMOTE_HOST,
           H.REMOTE_ADR,
           H.CDN_IP,
           H.CLIENT_IP,
           H.USER_AGENT,
           H.URL_QUERY_STRING,
           H.BROWSER_LANGUAGE,
           H.CLIENT_IP_ADDRESS,
           H.BROWSER_NAME,
           H.AUTH_PASSWORD
    FROM EEFISA.TAUD_ACTIVITY_LOG_HIS H
    LEFT JOIN EEFISA.TGEN_CATALOGUE_ITEM CT ON ( H.EVENT_TYPE = CT.ITEM_ID
                                                 AND CT.CATALOGUE_ID = 1 )
    LEFT JOIN SELECTBT ON ( SELECTBT.BUSINESS_TEMPLATE_ID = H.BUSINESS_TEMPLATE_ID )
    LEFT JOIN SELECTQT ON ( SELECTQT.QUERY_TEMPLATE_ID = H.QUERY_TEMPLATE_ID )
--WHERE TRUNC(RECORD_DATE) BETWEEN TO_DATE(:P_FECHAHORA_INICIO,'YYYYMMDDHH24MISS') AND TO_DATE(:P_FECHAHORA_FINAL,'YYYYMMDDHH24MISS') 
    WHERE H.RECORD_DATE BETWEEN NVL(TO_DATE(SYS_CONTEXT('Generic_ctx','P_FECHAHORA_INICIO'),'YYYYMMDDHH24MISS'),TRUNC(SYSDATE) - 10) AND NVL(TO_DATE(SYS_CONTEXT('Generic_ctx','P_FECHAHORA_FINAL'),'YYYYMMDDHH24MISS'),TRUNC(SYSDATE) + 1)
          AND   H.INTERNAL_SESSION_ID BETWEEN NVL(TO_NUMBER(SYS_CONTEXT('Generic_ctx','P_INTERNAL_SESSION_ID_INICIO') ),0) AND NVL(TO_NUMBER(SYS_CONTEXT('Generic_ctx','P_INTERNAL_SESSION_ID_FINAL') ),999999999999999999)
--WHERE TRUNC(RECORD_DATE) = TRUNC(SYSDATE - 1) and user_id=:user_id 
;
     
GRANT SELECT ON EAPPFISA.Set_Generic_ctx TO EEFISA;
/
GRANT SELECT ON EEFISA.SSS_NO_MONETARIA_OMNIA_QUERY TO EAPPFISA;       
/
CREATE OR REPLACE SYNONYM EAPPFISA.SSS_NO_MONETARIA_OMNIA_QUERY FOR EEFISA.SSS_NO_MONETARIA_OMNIA_QUERY;
/

SELECT TO_CHAR(A.INTERNAL_SESSION_ID) ||'-' ||TO_CHAR(A.RECORD_NUMBER)  AS NO_TRX,
         A.RECORD_DATE AS FECHA,
         A.SHORT_NAME_BT AS TIPO_TRX,
         A.SHORT_NAME_BT AS CATEG_TRANS,
         A.EVENTO AS EVENTO,
         NULL AS ESTATUS,
         'BANCA EN LINEA' AS CANAL,
         NULL AS OFICINA_DEL_TRANSACCION,
         NULL AS TIPO_CLIENTE,
         NULL AS NO_CONTRATO,
         NULL AS COD_COMERCIO,
         NULL AS NOMBRE_COMERCIO,
         NULL AS NO_SOCIO,
         NULL AS NO_SUCURSAL_SOCIO,
         NULL AS NO_AGENCIA,
         NULL AS COD_CAJERO,
         NULL AS NUMERO_SIB,
         NULL AS COD_OPERACION_SIB,
         TO_CHAR(A.USER_ID) AS NO_SESION,
         NULL AS NO_APROBACION_TARJETA,
         NULL AS COD_TRX_PROCESADOR,
         NULL AS COD_PROCESADOR,
         NULL AS NOMBRE_RED,
         NULL AS NO_CTA_ORIGEN,
         NULL AS TIPO_CTA_ORIGEN,
         NULL AS NO_CTA_DESTINO,
         NULL AS TIPO_CTA_DESTINO,
         NULL AS CTA_ENTIDAD_REMITENTE,
         NULL AS CLIENTE_REMITENTE,
         NULL AS TIPO_ID_REMITENTE,
         NULL AS ENTIDAD_REMITENTE,
         NULL AS CTA_ENTIDAD_RECEPTORA,
         NULL AS CLIENTE_RECEPTOR,
         NULL AS TIPO_ID_RECEPTOR,
         NULL AS IDENTI_RECEPTOR,
         NULL AS ENTIDAD_RECEPTORA,
         NULL AS EMAIL,
         NULL AS ESTATUS_CUENTA,
         A.SIGN_ON_NAME AS REFERENCIA_USUARIO,
         NULL AS MONEDA_ORIGEN,
         NULL AS MONTO_ORIGEN,
         NULL AS MONEDA_DESTINO,
         NULL AS MONTO_DESTINO,
         NULL AS SUBTOTAL,
         NULL AS MONTO_COMISION_USUARIO,
         NULL AS IMPUESTO,
         NULL AS MONTO_IMPUESTO,
         NULL AS MONTO_IMPUESTO_2_,
         NULL AS COMISION_EN_LINEA,
         A.SHORT_NAME_BT AS DETALLE_TRX,
         NULL AS REFERENCIA,
         NULL AS ENVIA_NOTIFICACION,
         NULL AS EMAIL_BENEFICIARIO,
         A.SIGN_ON_NAME AS USUARIO,
         NULL AS COD_RESPUESTA_BACKEND,
         NULL AS DESCRIPCION_BACKEND,
         NULL AS NO_APROBACION_TRADER,
         NULL AS CATEGORIA_CTA_ORIGEN,
         NULL AS SUBCATEGORIA_CTA_ORIGEN,
         NULL AS CATEGORIA_CTA_DESTINO,
         NULL AS SUBCATEGORIA_CTA_DESTINO,
         NULL AS RESPONSABLE
         --select a.*
  FROM EEFISA.SSS_NO_MONETARIA_OMNIA_QUERY A
ORDER BY A.INTERNAL_SESSION_ID DESC, A.RECORD_NUMBER, A.EVENT_TYPE 
;

--SELECT MAX(RECORD_DATE) FROM TAUD_ACTIVITY_LOG_HIS;

--SELECT CT.VALUE FROM TGEN_CATALOGUE_ITEM CT WHERE CT.CATALOGUE_ID = 1;