--SSS_NO_MONETARIA_OMNIA_CREATE_TABLE.sql
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
use DBIntermediaGeolocalizacion;

DROP TABLE SSS_NO_MONETARIA_OMNIA;

CREATE TABLE SSS_NO_MONETARIA_OMNIA(
No_trx	Varchar(50),
Fecha	datetime,
Tipo_trx	Varchar(250),
Categ_Trans	Varchar(250),
Evento	Varchar(80),
Estatus	Varchar(50),
Canal	Varchar(50),
Oficina_del_Transaccion	Varchar(50),
Tipo_Cliente	Varchar(50),
No_Contrato	Varchar(50),
No_Terminal	Varchar(50),
COD_Comercio	Varchar(50),
Nombre_Comercio	Varchar(50),
No_Socio	Varchar(50),
No_Sucursal_Socio	Varchar(50),
No_Agencia	Varchar(50),
COD_Cajero	Varchar(50),
Numero_SIB	Varchar(50),
COD_Operacion_SIB	Varchar(50),
No_Sesion	Varchar(50),
No_Aprobacion_Tarjeta	Varchar(50),
COD_TRX_Procesador	Varchar(50),
COD_Procesador	Varchar(50),
Nombre_Red	Varchar(50),
No_CTA_Origen	Varchar(50),
Tipo_CTA_Origen	Varchar(50),
No_CTA_Destino	Varchar(50),
Tipo_CTA_Destino	Varchar(50),
CTA_entidad_remitente	Varchar(50),
cliente_remitente	Varchar(50),
Tipo_ID_remitente	Varchar(50),
Entidad_remitente	Varchar(50),
CTA_entidad_receptora	Varchar(50),
cliente_receptor	Varchar(50),
Tipo_ID_receptor	Varchar(50),
IDENTI_receptor	Varchar(50),
Entidad_receptora	Varchar(50),
Email	Varchar(256),
Estatus_cuenta	Varchar(50),
Referencia_Usuario	Varchar(50),
Moneda_Origen	Varchar(6),
Monto_Origen	DECIMAL(18,4),
Moneda_Destino	Varchar(6),
Monto_Destino	DECIMAL(18,4),
Subtotal	DECIMAL(18,4),
Monto_Comision_Usuario	DECIMAL(18,4),
Impuesto	DECIMAL(18,4),
Monto_Impuesto	DECIMAL(18,4),
Monto_Impuesto_2_	DECIMAL(18,4),
Comision_En_Linea	Varchar(50),
Detalle_trx	Varchar(250),
Referencia	Varchar(50),
Envia_Notificacion	INT,
Email_Beneficiario	Varchar(256),
Usuario	Varchar(50),
COD_Respuesta_Backend	Varchar(8000),
Descripcion_Backend	Varchar(8000),
No_Aprobacion_Trader	Varchar(50),
Categoria_CTA_Origen	Varchar(50),
SubCategoria_CTA_Origen	Varchar(50),
Categoria_CTA_Destino	Varchar(50),
SubCategoria_CTA_Destino	Varchar(50),
Responsable	Varchar(50)
);

-- DBIntermediaGeolocalizacion.dbo.SSS_NO_MONETARIA_OMNIA definition

-- Drop table

-- DROP TABLE DBIntermediaGeolocalizacion.dbo.SSS_NO_MONETARIA_OMNIA;

/*CREATE TABLE DBIntermediaGeolocalizacion.dbo.SSS_NO_MONETARIA_OMNIA (
	No_trx varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Fecha datetime NULL,
	Tipo_trx varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Categ_Trans varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Evento varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Estatus varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Canal varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Oficina_del_Transaccion varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Tipo_Cliente varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	No_Contrato varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	No_Terminal varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COD_Comercio varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Nombre_Comercio varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	No_Socio varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	No_Sucursal_Socio varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	No_Agencia varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COD_Cajero varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Numero_SIB varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COD_Operacion_SIB varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	No_Sesion varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	No_Aprobacion_Tarjeta varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COD_TRX_Procesador varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COD_Procesador varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Nombre_Red varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	No_CTA_Origen varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Tipo_CTA_Origen varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	No_CTA_Destino varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Tipo_CTA_Destino varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CTA_entidad_remitente varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	cliente_remitente varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Tipo_ID_remitente varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Entidad_remitente varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CTA_entidad_receptora varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	cliente_receptor varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Tipo_ID_receptor varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	IDENTI_receptor varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Entidad_receptora varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Email varchar(256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Estatus_cuenta varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Referencia_Usuario varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Moneda_Origen varchar(6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Monto_Origen decimal(18,4) NULL,
	Moneda_Destino varchar(6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Monto_Destino decimal(18,4) NULL,
	Subtotal decimal(18,4) NULL,
	Monto_Comision_Usuario decimal(18,4) NULL,
	Impuesto decimal(18,4) NULL,
	Monto_Impuesto decimal(18,4) NULL,
	Monto_Impuesto_2_ decimal(18,4) NULL,
	Comision_En_Linea varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Detalle_trx varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Referencia varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Envia_Notificacion int NULL,
	Email_Beneficiario varchar(256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Usuario varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COD_Respuesta_Backend varchar(8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Descripcion_Backend varchar(8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	No_Aprobacion_Trader varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Categoria_CTA_Origen varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SubCategoria_CTA_Origen varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Categoria_CTA_Destino varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SubCategoria_CTA_Destino varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Responsable varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
);*/